/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 --transform public/models/pizzapan.glb 
Files: public/models/pizzapan.glb [6.01MB] > C:\Users\dilwa\OneDrive\Desktop\piz\pizzapan-transformed.glb [3.93MB] (35%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pizzapan-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.18, 1.768, 0.091]} rotation={[0.155, 0.56, -0.13]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.crust} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.sauce} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.pepperoni} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.onions} />
        <mesh geometry={nodes.Cube004_4.geometry} material={materials.olives} />
        <mesh geometry={nodes.Cube004_5.geometry} material={materials.cheese} />
        <mesh geometry={nodes.Cube004_6.geometry} material={materials['basil.001']} />
      </group>
      <mesh geometry={nodes.pan.geometry} material={materials['Material.018']} position={[0, -0.507, 0]} rotation={[0, 0.466, 0]} scale={[0.838, 1, 0.838]} />
    </group>
  )
}

useGLTF.preload('/pizzapan-transformed.glb')
