/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 --transform public/models/pizza.glb 
Files: public/models/pizza.glb [5.49MB] > C:\Users\dilwa\OneDrive\Desktop\piz\pizza-transformed.glb [3.84MB] (30%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pizza(props) {
  const { nodes, materials } = useGLTF('models/pizza-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.18, 2.05, 0.091]} rotation={[0.208, 0.574, -0.114]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube004_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube004_5.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube004_6.geometry} material={materials['basil.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/pizza-transformed.glb')
